name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          git-message: 'chore(release): {version}'
          git-user-name: 'Conventional Changelog Action'
          git-user-email: 'conventional.changelog.action@github.com'
          git-pull-method: '--ff-only'
          git-push: true
          git-branch: 'refs/heads/main'
          preset: 'angular'
          tag-prefix: 'v'
          output-file: 'CHANGELOG.md'
          release-count: 5
          version-file: './package.json'
          version-path: 'version'
          skip-git-pull: false
          skip-on-empty: false
          skip-version-file: false
          skip-commit: false
          skip-tag: false
          git-url: 'github.com'
          skip-ci: true
          create-summary: false
          pre-release: false
          pre-release-identifier: 'rc'
          skip-bump: false